### ISSUE TITLE
estimate_poses script can't find data when repo is pip installed in Colab

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/mediapipe-hand-crop-fix#1]
![image](https://github.com/sign-language-processing/mediapipe-hand-crop-fix/assets/122366389/e096b88a-d44d-4b5c-bc0d-6d0ad0ebe12f)

Readme says to (1) pip install the the github repo, (2) download/extract Panoptic dataset, then to run estimator. However, the estimator script looks for the data based on where the script is, and when the repo gets pip installed, the actual script that gets run is in, like, /usr/lib. 

Here's the estimator script's code to look for data: https://github.com/sign-language-processing/mediapipe-hand-crop-fix/blob/main/mediapipe_crop_estimate/estimate_poses.py#L7-L8

So then it'll go up two and look for "data" and find nothing for the hand labels or the panoptic, and you get results with, like tqdm just showing "0/0". 

In Colab, after pip installing, the script will live at `/usr/local/lib/python3.10/dist-packages/mediapipe_crop_estimate/` estimate_poses.py, so the code will look in `"/usr/local/lib/python3.10/ " / "data"` which is not a directory. 

Probably an argparse arg with path to the data dir would fix it, or if we didn't install the repo but instead did a requirements.txt or something?

**Comment by cleong110** [comment]
My Colab script where I ran into this issue: https://colab.research.google.com/drive/15UnPD4xLQRRsuRSHZkRP9n5qFiWBK7jj?usp=sharing

**Comment by cleong110** [comment]
When I edited /usr/local/lib/python3.10/dist-packages/mediapipe_crop_estimate/estimate_poses.py manually, I got past this error: 
![image](https://github.com/sign-language-processing/mediapipe-hand-crop-fix/assets/122366389/e8841d37-66a1-4f5e-a075-7d79e093dcb2)

**Comment by AmitMY** [comment]
I think that's a documentation issue.
When using this repo, one should clone and not install.
Updated the README https://github.com/sign-language-processing/mediapipe-hand-crop-fix/commit/f0b0b08990ea887b3cd462fbaf09c425b1ece6d1

**Comment by cleong110** [comment]
That makes sense, was wondering if that was the intention as a number of the steps implied it, e.g. "cd data"

**Comment by cleong110** [comment]
I guess that fixes this issue then, I will test out the clone method when I get a chance
