### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by herochen7372** [sign-language-processing/mediapipe-hand-crop-fix#2]
Hi，could you provide a demo and pretrain model？

**Comment by AmitMY** [comment]
The model from the paper can be found in https://github.com/sign-language-processing/mediapipe-hand-crop-fix/tree/main/mediapipe_crop_estimate/mlp
To run it, compared to the original baseline, use this script
https://github.com/sign-language-processing/mediapipe-hand-crop-fix/blob/main/mediapipe_crop_estimate/evaluate.py

This repository is meant for the research of the hand crop. If you are looking for the full mediapipe pipeline including this model, this is not the place. It will need to be implemented in the pipeline: https://github.com/google/mediapipe/issues/5373
